### ISSUE TITLE
help: runing it on nodejs

### ISSUE THREAD

**Issue by souzaramon** [phiresky/sql.js-httpvfs#16]
Well, this lib seams to be very promissing to solve my current problem.

I want to run it on aws-lambda, but the WebWorkers are not suported in nodejs, I'm planing to fork this repo in order to make a synchronous version, I understand your code in a surface level, so can I ask u for a ideia on how make it work?

I meann, it seams to be possible, but I'm not sure about this part right here

`vtab.ts`
```ts
  // send message to main thread
  (self as DedicatedWorkerGlobalScope).postMessage({
    action: "eval",
    notify: sab,
    request,
  });
```
I'll be very happy with anything you could say about it
thanks

**Comment by phiresky** [comment]
The code in vtab.ts is not required at all for the httpvfs functionality, that's purely for the DOM-as-an-SQL-table demo. I've added a comment to make that more clear, but maybe I should remove it from this repo entirely at some point.

Other than that, running this whole thing in node is _probably_ possible with major modifications, but it's probably not a great idea - if your code is running natively you can use a native SQLite build instead of one compiled to WASM. There's for example [sqlite_web_vfs](https://github.com/mlin/sqlite_web_vfs) which is very similar to this project except it uses native SQLite.

**Comment by phiresky** [comment]
I've added some more info to the README about related work and the limitations. 

The need for webworkers is because SQLite is synchronous, so the HTTP requests need to be synchronous - which is a bad idea on the main thread in both the browser as well as node. If you want to make it work without threads but still without native code, you should probably base it off [wa-sqlite](https://github.com/rhashimoto/wa-sqlite) which solves that with asyncify. Can't say exactly what would need to be done to make it work in node though.

I'll close this because node support is out of scope here. Let me know if I can help in any other way.
