### ISSUE TITLE
HTTP/2 support

### ISSUE THREAD

**Issue by mycall** [phiresky/sql.js-httpvfs#5]
Any chance to support HTTP/2 channels for a possibly faster VFS?

**Comment by phiresky** [comment]
It is already using HTTP/2:
![image](https://user-images.githubusercontent.com/2303841/117123200-06c25c80-ad97-11eb-90f7-e08e24dfe594.png)

The protocol used is not controlled from within this code though. The benefit of HTTP2 is also fairly minor for this because SQLite does not do threaded read requests, so all HTTP requests are fully sequential in any case. I don't think there's really a solution to this without forking SQLite itself
