### ISSUE TITLE
Any way to optimize this recursive query?

### ISSUE THREAD

**Issue by wcedmisten** [phiresky/sql.js-httpvfs#53]
Hello!

I have a sqlite DB that represents a DAG. It has two tables, `node` and `edge`, where node has some extra data about each node and `edge` has a `node_to` and `node_from` FK to `node.id`. 

I created a query to get all the "ancestors" of a certain node. I initially tried running this query with sqlite.js-httpvfs, but the query took about 30 seconds to run, even with local HTTP access. I think the reason was because of poor spatial locality requiring a SCAN of the DB.

Is there any way to optimize this query to minimize SCAN?

```sql
WITH RECURSIVE
    ancestor(n) AS (
      VALUES(?)
      UNION ALL
      SELECT node_from FROM edge, ancestor
      WHERE edge.node_to=ancestor.n
    )
    SELECT node_from,node_to,node.* FROM edge
    JOIN node ON node_from = node.id WHERE graph_edge.node_to IN ancestor;
```

Here is the query plan for the query:
```
QUERY PLAN
|--SCAN edge
|--LIST SUBQUERY 3
|  |--CO-ROUTINE ancestor
|  |  |--SETUP
|  |  |  `--SCAN CONSTANT ROW
|  |  `--RECURSIVE STEP
|  |     |--SCAN ancestor
|  |     `--SEARCH edge USING AUTOMATIC COVERING INDEX (node_to=?)
|  `--SCAN ancestor
`--SEARCH node USING INDEX sqlite_autoindex_node_1 (id=?)
```

As a workaround, I've just exported the data to JSON, because it actually wasn't that big, but I'm curious if this could be optimized to work.

**Comment by phiresky** [comment]
Interesting. I'm not sure to be honest. I'd say probably it isn't possible because this query can really only be done with almost completely random access (so it'll also be slow in normal SQLite except that the whole thing is fully in ram quickly). 

It'll only be quick if you find a way to index the data in a linear way. Often that's the case, but in general not. That is, basically if you find a order for your nodes where mostly the paths you're looking for is in order. Or if you can enumerate all paths a user could possibly want to find subpaths for.  Or e.g. if you can usefully order them in BFS or DFS order.

Then you'd store the order in your db and add a normal index. 

There's also some extensions for SQlite for e.g. spatial indexing that might be useful, but I don't have enough knowledge about those.

**Comment by wcedmisten** [comment]
Yeah it seems like there's not really a good way to cluster the data without a lot of duplication that would kind of destroy the flexibility of using a relational database. Anyway, thanks for the response, I'm still in awe of this project even though it doesn't quite fit my use-case.

It seems like it could still be very useful if I need to set up a bigger dataset with static hosting (that can use simpler queries).
